### ISSUE TITLE
Does not work on current ev3dev

### ISSUE THREAD

**Issue by akhayyat** [cavenel/ev3dev_examples#4]
I spent many hours trying to get this code to work on the current ev3dev distribution (not to mention building the Rubik solver Lego robot). I came to the conclusion that it needs major work to get it to work.

After fixing the device driver instantiations (`Motor` and `Color_sensor`), doing any actions failed due to the no longer existing `run_mode` files in the sysfs.

Is there any chance this project will get fixed and be operational again?

**Comment by cavenel** [comment]
Unfortunately there as been some major changes in ev3dev since this was programmed. I will not have time to fix the problem in the near future but any help on that would be welcome!
The code is using python functions (rotate_forever, rotate_time, rotate_position, goto_position) that are now way easier to implement. So changing these functions should not be too complicated.

I am sorry you spent so much time on this and will make clear on the project page that the code is for an old version of ev3dev.

**Comment by akhayyat** [comment]
Would it be possible to link to an earlier ev3dev release with which this code will work as is?

**Comment by dwalton76** [comment]
I noticed the same thing earlier this week. I forked it and will send a pull request once I am finished (hopefully later this week). My fork is https://github.com/dwalton76/ev3dev_examples

**Comment by dwalton76** [comment]
@cavenel where can I find the twophase.py that is referenced in the code?  I have all of the basics working, am working now on improving the color detection.

**Comment by dwalton76** [comment]
I'm guessing it is this:
https://github.com/unixpickle/Rubiks/tree/master/solver/kociemba

**Comment by cavenel** [comment]
Wow nice I will merge your fork asap thank you!! :)
For twophase.py on the computer (in case you don't want just basic solver on ev3 but two phase on the computer with less moves) it is not the one from unixpickle but a personal python code launching a binary twophase (under linux) with the correct options.
Both files are here: https://www.dropbox.com/s/dblms3bs2ivc70i/twophase.tar.gz?dl=1
If any problem with those, please open a new issue.

**Comment by cavenel** [comment]
About the color detection, my cube was with different color than most cubes. So the color detection may not be the best for other colors. But it was a very interesting problem and I spent quite a lot of nights on it ;) I am really curious to see your improvements!

**Comment by dwalton76** [comment]
ok pull request sent.  Probably the bigggest change is with resolving colors:
- using CIE76 to calculate the distance between two colors (CIE2000 takes 3x as long on ev3)
- grab the color for the middle squares
- compare the other 48 squares vs those six to find the closest match
- lots of sanity checks (does an edge/corner have two squares of the same color), do we have duplicate edges with the same pairs of colors, do we have duplicate corners, do we have impossible color combinations (U and D on an edge for instance), use cube_ev3 to check for parity, run through many permutations of how to match the colors that results in the least overall color distance, etc.

In my last ~20 scans I've only hit one color detection error so so far so good.

**Comment by dwalton76** [comment]
@cavenel you should be able to close this ticket.  Any objections to me taking the code here and adding it to a MINDCUB3R directory in https://github.com/rhempel/ev3dev-lang-python/tree/develop/demo

It would be nice to get the big demos all in one place
